// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/orca/orca.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ORCAClient is the client API for ORCA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ORCAClient interface {
	Orca(ctx context.Context, in *ORCARequest, opts ...grpc.CallOption) (*ORCAResponse, error)
}

type oRCAClient struct {
	cc grpc.ClientConnInterface
}

func NewORCAClient(cc grpc.ClientConnInterface) ORCAClient {
	return &oRCAClient{cc}
}

func (c *oRCAClient) Orca(ctx context.Context, in *ORCARequest, opts ...grpc.CallOption) (*ORCAResponse, error) {
	out := new(ORCAResponse)
	err := c.cc.Invoke(ctx, "/orca.ORCA/Orca", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ORCAServer is the server API for ORCA service.
// All implementations must embed UnimplementedORCAServer
// for forward compatibility
type ORCAServer interface {
	Orca(context.Context, *ORCARequest) (*ORCAResponse, error)
	mustEmbedUnimplementedORCAServer()
}

// UnimplementedORCAServer must be embedded to have forward compatible implementations.
type UnimplementedORCAServer struct {
}

func (UnimplementedORCAServer) Orca(context.Context, *ORCARequest) (*ORCAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Orca not implemented")
}
func (UnimplementedORCAServer) mustEmbedUnimplementedORCAServer() {}

// UnsafeORCAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ORCAServer will
// result in compilation errors.
type UnsafeORCAServer interface {
	mustEmbedUnimplementedORCAServer()
}

func RegisterORCAServer(s grpc.ServiceRegistrar, srv ORCAServer) {
	s.RegisterService(&ORCA_ServiceDesc, srv)
}

func _ORCA_Orca_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ORCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ORCAServer).Orca(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orca.ORCA/Orca",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ORCAServer).Orca(ctx, req.(*ORCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ORCA_ServiceDesc is the grpc.ServiceDesc for ORCA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ORCA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orca.ORCA",
	HandlerType: (*ORCAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Orca",
			Handler:    _ORCA_Orca_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orca/orca.proto",
}
