//
//protoc --go_out=. --go_opt=paths=source_relative \
//--proto_path="./.." \
//--proto_path="."  \
//--go-grpc_out=. \
//--go-grpc_opt=paths=source_relative \
//./proto/lalb/lalb.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/lalb/lalb.proto

package proto

import (
	proto "github.com/dmw2151/go-failure/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeHealthRequest
type NodeHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit        int64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Threshold    float64 `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	ServiceLabel string  `protobuf:"bytes,3,opt,name=serviceLabel,proto3" json:"serviceLabel,omitempty"`
}

func (x *NodeHealthRequest) Reset() {
	*x = NodeHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lalb_lalb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthRequest) ProtoMessage() {}

func (x *NodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lalb_lalb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthRequest.ProtoReflect.Descriptor instead.
func (*NodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_lalb_lalb_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHealthRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NodeHealthRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *NodeHealthRequest) GetServiceLabel() string {
	if x != nil {
		return x.ServiceLabel
	}
	return ""
}

// NodeHealthStatus
type NodeHealthStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr      string  `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Suspicion float64 `protobuf:"fixed64,2,opt,name=suspicion,proto3" json:"suspicion,omitempty"`
}

func (x *NodeHealthStatus) Reset() {
	*x = NodeHealthStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lalb_lalb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeHealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthStatus) ProtoMessage() {}

func (x *NodeHealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lalb_lalb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthStatus.ProtoReflect.Descriptor instead.
func (*NodeHealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_lalb_lalb_proto_rawDescGZIP(), []int{1}
}

func (x *NodeHealthStatus) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeHealthStatus) GetSuspicion() float64 {
	if x != nil {
		return x.Suspicion
	}
	return 0
}

// NodeHealthResponse
type NodeHealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statuses []*NodeHealthStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
}

func (x *NodeHealthResponse) Reset() {
	*x = NodeHealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lalb_lalb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthResponse) ProtoMessage() {}

func (x *NodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lalb_lalb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthResponse.ProtoReflect.Descriptor instead.
func (*NodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_lalb_lalb_proto_rawDescGZIP(), []int{2}
}

func (x *NodeHealthResponse) GetStatuses() []*NodeHealthStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_proto_lalb_lalb_proto protoreflect.FileDescriptor

var file_proto_lalb_lalb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6c, 0x62, 0x2f, 0x6c, 0x61, 0x6c,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x61, 0x6c, 0x62, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6b, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x44, 0x0a, 0x10,
	0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x73, 0x70, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x73, 0x75, 0x73, 0x70, 0x69, 0x63, 0x69,
	0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x61, 0x6c,
	0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x32, 0x7d, 0x0a, 0x09,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x42, 0x65, 0x61,
	0x74, 0x12, 0x0d, 0x2e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x61, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x6c, 0x62, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x61, 0x6c, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_lalb_lalb_proto_rawDescOnce sync.Once
	file_proto_lalb_lalb_proto_rawDescData = file_proto_lalb_lalb_proto_rawDesc
)

func file_proto_lalb_lalb_proto_rawDescGZIP() []byte {
	file_proto_lalb_lalb_proto_rawDescOnce.Do(func() {
		file_proto_lalb_lalb_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lalb_lalb_proto_rawDescData)
	})
	return file_proto_lalb_lalb_proto_rawDescData
}

var file_proto_lalb_lalb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_lalb_lalb_proto_goTypes = []interface{}{
	(*NodeHealthRequest)(nil),  // 0: lalb.NodeHealthRequest
	(*NodeHealthStatus)(nil),   // 1: lalb.NodeHealthStatus
	(*NodeHealthResponse)(nil), // 2: lalb.NodeHealthResponse
	(*proto.Beat)(nil),         // 3: failure.Beat
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
}
var file_proto_lalb_lalb_proto_depIdxs = []int32{
	1, // 0: lalb.NodeHealthResponse.statuses:type_name -> lalb.NodeHealthStatus
	3, // 1: lalb.HeartBeat.Beat:input_type -> failure.Beat
	0, // 2: lalb.HeartBeat.HealthyNodes:input_type -> lalb.NodeHealthRequest
	4, // 3: lalb.HeartBeat.Beat:output_type -> google.protobuf.Empty
	2, // 4: lalb.HeartBeat.HealthyNodes:output_type -> lalb.NodeHealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lalb_lalb_proto_init() }
func file_proto_lalb_lalb_proto_init() {
	if File_proto_lalb_lalb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lalb_lalb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lalb_lalb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeHealthStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lalb_lalb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeHealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lalb_lalb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lalb_lalb_proto_goTypes,
		DependencyIndexes: file_proto_lalb_lalb_proto_depIdxs,
		MessageInfos:      file_proto_lalb_lalb_proto_msgTypes,
	}.Build()
	File_proto_lalb_lalb_proto = out.File
	file_proto_lalb_lalb_proto_rawDesc = nil
	file_proto_lalb_lalb_proto_goTypes = nil
	file_proto_lalb_lalb_proto_depIdxs = nil
}
