// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/lalb/lalb.proto

package proto

import (
	context "context"
	proto "github.com/dmw2151/go-failure/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HeartBeatClient is the client API for HeartBeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartBeatClient interface {
	Beat(ctx context.Context, in *proto.Beat, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HealthyNodes(ctx context.Context, in *NodeHealthRequest, opts ...grpc.CallOption) (*NodeHealthResponse, error)
}

type heartBeatClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartBeatClient(cc grpc.ClientConnInterface) HeartBeatClient {
	return &heartBeatClient{cc}
}

func (c *heartBeatClient) Beat(ctx context.Context, in *proto.Beat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lalb.HeartBeat/Beat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartBeatClient) HealthyNodes(ctx context.Context, in *NodeHealthRequest, opts ...grpc.CallOption) (*NodeHealthResponse, error) {
	out := new(NodeHealthResponse)
	err := c.cc.Invoke(ctx, "/lalb.HeartBeat/HealthyNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartBeatServer is the server API for HeartBeat service.
// All implementations must embed UnimplementedHeartBeatServer
// for forward compatibility
type HeartBeatServer interface {
	Beat(context.Context, *proto.Beat) (*emptypb.Empty, error)
	HealthyNodes(context.Context, *NodeHealthRequest) (*NodeHealthResponse, error)
	mustEmbedUnimplementedHeartBeatServer()
}

// UnimplementedHeartBeatServer must be embedded to have forward compatible implementations.
type UnimplementedHeartBeatServer struct {
}

func (UnimplementedHeartBeatServer) Beat(context.Context, *proto.Beat) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Beat not implemented")
}
func (UnimplementedHeartBeatServer) HealthyNodes(context.Context, *NodeHealthRequest) (*NodeHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthyNodes not implemented")
}
func (UnimplementedHeartBeatServer) mustEmbedUnimplementedHeartBeatServer() {}

// UnsafeHeartBeatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartBeatServer will
// result in compilation errors.
type UnsafeHeartBeatServer interface {
	mustEmbedUnimplementedHeartBeatServer()
}

func RegisterHeartBeatServer(s grpc.ServiceRegistrar, srv HeartBeatServer) {
	s.RegisterService(&HeartBeat_ServiceDesc, srv)
}

func _HeartBeat_Beat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Beat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartBeatServer).Beat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lalb.HeartBeat/Beat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartBeatServer).Beat(ctx, req.(*proto.Beat))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeartBeat_HealthyNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartBeatServer).HealthyNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lalb.HeartBeat/HealthyNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartBeatServer).HealthyNodes(ctx, req.(*NodeHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeartBeat_ServiceDesc is the grpc.ServiceDesc for HeartBeat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeartBeat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lalb.HeartBeat",
	HandlerType: (*HeartBeatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Beat",
			Handler:    _HeartBeat_Beat_Handler,
		},
		{
			MethodName: "HealthyNodes",
			Handler:    _HeartBeat_HealthyNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lalb/lalb.proto",
}
