// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/lalb.proto

package proto

import (
	context "context"
	proto "github.com/dmw2151/go-failure/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LBClient is the client API for LB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LBClient interface {
	Beat(ctx context.Context, in *proto.Beat, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type lBClient struct {
	cc grpc.ClientConnInterface
}

func NewLBClient(cc grpc.ClientConnInterface) LBClient {
	return &lBClient{cc}
}

func (c *lBClient) Beat(ctx context.Context, in *proto.Beat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/echo.LB/Beat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LBServer is the server API for LB service.
// All implementations must embed UnimplementedLBServer
// for forward compatibility
type LBServer interface {
	Beat(context.Context, *proto.Beat) (*emptypb.Empty, error)
	mustEmbedUnimplementedLBServer()
}

// UnimplementedLBServer must be embedded to have forward compatible implementations.
type UnimplementedLBServer struct {
}

func (UnimplementedLBServer) Beat(context.Context, *proto.Beat) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Beat not implemented")
}
func (UnimplementedLBServer) mustEmbedUnimplementedLBServer() {}

// UnsafeLBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LBServer will
// result in compilation errors.
type UnsafeLBServer interface {
	mustEmbedUnimplementedLBServer()
}

func RegisterLBServer(s grpc.ServiceRegistrar, srv LBServer) {
	s.RegisterService(&LB_ServiceDesc, srv)
}

func _LB_Beat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Beat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LBServer).Beat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.LB/Beat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LBServer).Beat(ctx, req.(*proto.Beat))
	}
	return interceptor(ctx, in, info, handler)
}

// LB_ServiceDesc is the grpc.ServiceDesc for LB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.LB",
	HandlerType: (*LBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Beat",
			Handler:    _LB_Beat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lalb.proto",
}
