version: '3'

services:

  prom:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    links:
      - phi_failure_detector:phi_failure_detector
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    
  phi_failure_detector:
    image: dmw2151/phi-failure-server
    restart: unless-stopped
    expose:
      - 52150
    ports:
      - 52150:52150 # publish metrics endpoint
      - 52151:52151 # listen for health ping messages
    environment:
      - METRICS_SERVE_ADDR=0.0.0.0:52150
      - FAILURE_DETECTOR_LISTEN_ADDR=0.0.0.0:52151
    command:
      - ./server
    
volumes:
  prometheus_data: {}

